# Site settings
title: Kurum.in
email: nandosousafr@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Brazilian, Software developer and Science Groker.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kurum.in" # the base hostname & protocol for your site
twitter_username: nandosousafr
github_username:  nandosousafr

# Build settings
markdown: kramdown
